title: "Component Oriented PHP Tutorials"
description: Learn how to create PHP applications using standalone Composer packages instead of full frameworks.
remote_theme: "jekyll/minima@1e8a445"

plugins:
  - jekyll-remote-theme